name: Code check

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  linter:
    name: Linter
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'yarn'

      - name: Install packages
        run: |
          yarn install --pure-lockfile

      - name: Linter
        run: yarn lint-staged --diff=origin/main
